# Generated by Django 5.2.14 on 2026-05-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_category_product_color_product_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='category',
        ),
    ]
