# Generated by Django 5.2.6 on 2026-05-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_item_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
